apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://github.com/release-engineering/konflux-release-data-ci/pull/1","configuration-time":"Fri,
      13 Sep 2024 19:56:17 UTC"},"message":"done"}'
  creationTimestamp: "2024-09-13T19:56:09Z"
  finalizers:
  - test.appstudio.openshift.io/component
  - pac.component.appstudio.openshift.io/finalizer
  generation: 3
  name: konflux-release-data-ci
  namespace: releng-dev-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Application
    name: konflux-release-data-ci
    uid: 792bdbff-6e40-4cec-b043-0d555720a45f
  resourceVersion: "2287624406"
  uid: 090a6586-60d2-4871-8316-b791b4018137
spec:
  application: konflux-release-data-ci
  componentName: konflux-release-data-ci
  containerImage: quay.io/redhat-user-workloads/releng-dev-tenant/konflux-release-data-ci/konflux-release-data-ci@sha256:3f2cf78b78c787abec33e844b3888d797b8fbe8ab544403a62f0fa4f6550ae7f
  resources: {}
  source:
    git:
      context: ./src/
      dockerfileUrl: Containerfile
      url: https://github.com/release-engineering/konflux-release-data-ci
status:
  gitops: {}
  lastBuiltCommit: 9d217ee0113625d7570dd4b1a8d8d9a751cbc4c7
